barplot_sa_strength <- function(OUT_SIS = NA, which_m = "all", n_linksv = NA, type_data = "perc",
error_bars = "CI", size_lab = 0.8, names_lab = "yes", l_edges = 0.05, save_file = "pdf",
fname = "community"){
	##
	## error message if the input is not a list object with the following seven elements:
	## [1] matches_M
	## [2] tot_matches_M
	## [3] matches_pnz_M
	## [4] tot_matches_pnz_M
	## [5] matches_pn_M
	## [6] tot_matches_pn_M
	## [7] edgelist_w
	##
	nomilista <- c("matches_M", "tot_matches_M", "matches_pnz_M",
	"tot_matches_pnz_M", "matches_pn_M", "tot_matches_pn_M", "edgelist_w")
	{
	if(length(names(OUT_SIS)) == 0) l_ml <- 1
	else l_ml <- length(which(is.na(match(names(OUT_SIS),nomilista))==TRUE))
	}
	##
	{
	if(is.list(OUT_SIS) == TRUE){
		if(l_ml != 0){
			cat("\nerror: OUT_SIS must be a list generated by the function \"sa_interaction_strength\"")
			cat("\n\n")
			invisible(NULL)
		}
		##
		## barplot visualization
		else{
			##
			## total number of nodes
			tot_nodes <- length(unique(c(OUT_SIS[[7]][,1], OUT_SIS[[7]][,2])))
			tot_predi <- tot_nodes^2
			##
			V_spa <- 0
			##
			## type of scenario considered to identify changes in the sign of predictions
			whichm <- c("all", "pnz", "pn")
			whichm_m <- length(which(is.na(match(which_m, whichm))==FALSE))
			if(whichm_m != 1){
				cat("\nwarning: the user can decide whether to visualize the incidence of links in changes that:\n")
				cat("- involve any type of sign (i.e. \"+\", \"?+\", \"-\", \"?-\", \"0\" or \"0*\"; \"all\")\n")
				cat("- are related to three categories of signs (i.e. \"+\", \"-\" or \"0\"; \"pnz\")\n")
				cat("- classify responses as either positive (\"+\") or negative (\"-\") (i.e. \"pn\")\n")
				cat("which_m was reset to default option (i.e. \"all\")\n\n")
				which_m <- "all"
				V_spa <- 1
			}
			##
			## total number of links that trigger at least one mismatch with reference predictions
			if(which_m == "all"){
				nzpred <- which(OUT_SIS$tot_matches_M != 0)
				{
				if(length(nzpred)!=0){
					if(length(nzpred) > 1)M_bar <- OUT_SIS$matches_M[nzpred,]
					else M_bar <- matrix(OUT_SIS$matches_M, nrow = 1)
					}
				else{
					if(V_spa == 1)cat("error: no barplot generated as all values in matches_M are zero\n\n")
					else cat("\nerror: no barplot generated as all values in matches_M are zero\n\n")
					return(invisible(NULL))
					}
				}
			}
			if(which_m == "pnz"){
				nzpred <- which(OUT_SIS$tot_matches_pnz_M != 0)
				{
				if(length(nzpred)!=0){
					if(length(nzpred) > 1)M_bar <- OUT_SIS$matches_pnz_M[nzpred,]
					else M_bar <- matrix(OUT_SIS$matches_pnz_M, nrow = 1)
					}
				else{
					if(V_spa == 1)cat("error: no barplot generated as all values in matches_pnz_M are zero\n\n")
					else cat("\nerror: no barplot generated as all values in matches_pnz_M are zero\n\n")
					return(invisible(NULL))
					}
				}
			}
			if(which_m == "pn"){
				nzpred <- which(OUT_SIS$tot_matches_pn_M != 0)
				{
				if(length(nzpred)!=0){
					if(length(nzpred) > 1)M_bar <- OUT_SIS$matches_pn_M[nzpred,]
					else M_bar <- matrix(OUT_SIS$matches_pn_M, nrow = 1)
					}
				else{
					if(V_spa == 1)cat("error: no barplot generated as all values in matches_pn_M are zero\n\n")
					else cat("\nerror: no barplot generated as all values in matches_pn_M are zero\n\n")
					return(invisible(NULL))
					}
				}
			}
			##
			## number of links to consider for the barplot
			M_bar_rr <- nrow(M_bar)
			{
			if(length(n_linksv) > 1 | is.vector(n_linksv) == FALSE){
				if(V_spa == 1)cat("warning: the number of links visualized in the barplot must be an integer and strictly positive number\n")
				else cat("\nwarning: the number of links visualized in the barplot must be an integer and strictly positive number\n")
				cat("included between 1 and the number of rows (with at least one non-zero value) in the matrix of matches\n")
				cat("n_linksv was reset to default by including all possible links\n\n")
				n_linksv <- M_bar_rr
				V_spa <- 1
				}
			else{
				if(is.na(n_linksv) == TRUE){
					n_linksv <- M_bar_rr
					}
				else{
					if(is.numeric(n_linksv) == FALSE | n_linksv < 1 | n_linksv > M_bar_rr){
						if(V_spa == 1)cat("warning: the number of links visualized in the barplot must be an integer and strictly positive number\n")
						else cat("\nwarning: the number of links visualized in the barplot must be an integer and strictly positive number\n")
						cat("included between 1 and the number of rows (with at least one non-zero value) in the matrix of matches\n")
						cat("n_linksv was reset to default by including all possible links\n\n")
						n_linksv <- M_bar_rr
						V_spa <- 1
						}
					}
				}
			}
			##
			## the barplot can report either percentages or raw values
			type_datan <- c("perc", "raw")
			type_datan_m <- length(which(is.na(match(type_data, type_datan))==FALSE))
			if(type_datan_m != 1){
				if(V_spa == 1)cat("warning: the barplot can visualize either percentages (\"perc\") or raw data (\"raw\")\n")
				else cat("\nwarning: the barplot can visualize either percentages (\"perc\") or raw data (\"raw\")\n")
				cat("type_data was reset to default option (i.e. \"perc\")\n\n")
				type_data <- "perc"
				V_spa <- 1
			}
			##
			## information visualized with the error bars
			error_barsn <- c("sd", "SE", "CI")
			error_barsn_m <- length(which(is.na(match(error_bars, error_barsn))==FALSE))
			if(error_barsn_m != 1){
				if(V_spa == 1)cat("warning: error bars can visualize one of the following quantities:\n")
				else cat("\nwarning: error bars can visualize one of the following quantities:\n")
				cat("standard deviation (\"sd\"), standard error (\"SE\") or 95% confidence interval (\"CI\")\n")
				cat("error_bars was reset to default option (i.e. \"CI\")\n\n")
				error_bars <- "CI"
				V_spa <- 1
			}
			##
			## size of the names on the y-axis
			{
			if(length(size_lab) > 1 | is.vector(size_lab) == FALSE){
				if(V_spa == 1)cat("warning: the size of the names on the y-axis must be a strictly positive number\n")
				else cat("\nwarning: the size of the names on the y-axis must be a strictly positive number\n")
				cat("size_lab was reset to default value (i.e. 0.8)\n\n")
				size_lab <- 0.8
				V_spa <- 1
				}
			else{
				if(is.numeric(size_lab) == FALSE){
					if(V_spa == 1)cat("warning: the size of the names on the y-axis must be a strictly positive number\n")
					else cat("\nwarning: the size of the names on the y-axis must be a strictly positive number\n")
					cat("size_lab was reset to default value (i.e. 0.8)\n\n")
					size_lab <- 0.8
					V_spa <- 1
					}
				else if(size_lab <= 0){
					if(V_spa == 1)cat("warning: the size of the names on the y-axis must be a strictly positive number\n")
					else cat("\nwarning: the size of the names on the y-axis must be a strictly positive number\n")
					cat("size_lab was reset to default value (i.e. 0.8)\n\n")
					size_lab <- 0.8
					V_spa <- 1
					}
				}
			}
			##
			## decision whether to print names or numbers on the y-axis
			names_labn <- c("yes", "no")
			names_labn_m <- length(which(is.na(match(names_lab, names_labn))==FALSE))
			if(names_labn_m != 1){
				if(V_spa == 1)cat("warning: the user can decide whether to visualize on the y-axis link names (\"yes\") or integer numbers (\"no\"):\n")
				else cat("\nwarning: the user can decide whether to visualize on the y-axis link names (\"yes\") or integer numbers (\"no\"):\n")
				cat("names_lab was reset to default option (i.e. \"yes\")\n\n")
				names_lab <- "yes"
				V_spa <- 1
			}
			##
			## length of the edges of the error bars (in inches)
			{
			if(length(l_edges) > 1 | is.vector(l_edges) == FALSE){
				if(V_spa == 1)cat("warning: the length of the edges of the error bars must be a strictly positive number\n")
				else cat("\nwarning: the length of the edges of the error bars must be a strictly positive number\n")
				cat("l_edges was reset to default value (i.e. 0.05)\n\n")
				l_edges <- 0.05
				V_spa <- 1
				}
			else{
				if(is.numeric(l_edges) == FALSE){
					if(V_spa == 1)cat("warning: the length of the edges of the error bars must be a strictly positive number\n")
					else cat("\nwarning: the length of the edges of the error bars must be a strictly positive number\n")
					cat("l_edges was reset to default value (i.e. 0.05)\n\n")
					l_edges <- 0.05
					V_spa <- 1
					}
				else if(l_edges <= 0){
					if(V_spa == 1)cat("warning: the length of the edges of the error bars must be a strictly positive number\n")
					else cat("\nwarning: the length of the edges of the error bars must be a strictly positive number\n")
					cat("l_edges was reset to default value (i.e. 0.05)\n\n")
					l_edges <- 0.05
					V_spa <- 1
					}
				}
			}
			##
			{
			if(type_data == "perc"){
				M_bar_s1 <- 100 * M_bar/tot_predi
				xx_lab <- "%"
				}
			else{
				M_bar_s1 <- M_bar
				xx_lab <- "count"
				}
			}
			##
			mu_A <- apply(M_bar_s1,1,mean)
			sd_A <- apply(M_bar_s1,1,sd)
			SE_A <- sd_A/sqrt(ncol(M_bar_s1))
			CI_A <- 1.96 * SE_A
			##
			mu_A_s <- sort(mu_A, decreasing = TRUE)
			n_s <- names(mu_A_s)
			CI_A_s <- CI_A[n_s]
			SE_A_s <- SE_A[n_s]
			sd_A_s <- sd_A[n_s]
			##
			mu_A_f <- mu_A_s[1:n_linksv]
			CI_A_s <- CI_A[1:n_linksv]
			SE_A_s <- SE_A[1:n_linksv]
			sd_A_s <- sd_A[1:n_linksv]
			##
			if(error_bars == "CI")eb <- CI_A_s
			##
			if(error_bars == "SE")eb <- SE_A_s
			##
			if(error_bars == "sd")eb <- sd_A_s
			##
			limit <- (trunc(max(mu_A_f + eb)/5) + 1) * 5
			##
			## extension for saving the heatmap
			all_ext <- c("pdf","svg")
			{
			if(length(save_file) > 1 | is.vector(save_file) == FALSE){
				{
				if(V_spa == 1)cat("warning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
				else cat("\nwarning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
				}
				cat("\n")
				cat("the format was reset to default (i.e. \"pdf\")")
				cat("\n\n")
				save_file <- "pdf"
				V_spa <- 1
				}
			else{
				s_ext <- which(all_ext == save_file)
				if(length(s_ext) != 1){
					{
					if(V_spa == 1)cat("warning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
					else cat("\nwarning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
					}
					cat("\n")
					cat("the format was reset to default (i.e. \"pdf\")")
					cat("\n\n")
					save_file <- "pdf"
					V_spa <- 1
					}
				}
			}
			##
			## filename must be a unique element of type character
			{
			if(is.character(fname) == FALSE){
				if(V_spa == 1)cat("warning: the name of the image file must be of type \"character\"\n")
				else cat("\nwarning: the name of the image file must be of type \"character\"\n")
				cat("the name was reset to default option (i.e. \"community\")\n\n")
				fname <- "community"
				V_spa <- 1
				}
			else if(length(fname) > 1){
				if(V_spa == 1)cat("warning: the name of the image file must be a single element of type \"character\"\n")
				else cat("\nwarning: the name of the image file must be a single element of type \"character\"\n")
				cat("the name was reset to default option (i.e. \"community\")\n\n")
				fname <- "community"
				V_spa <- 1
				}
			}
			##
			## produce an svg file in the working directory
			{
			if(save_file == "svg"){
				file_name1 <- paste(fname, "_barplot_sa_strength.", save_file, sep = "")
				##
				svg(filename = file_name1)
				##
				{
				if(names_lab == "yes"){
					ima <- barplot(mu_A_f[length(mu_A_f):1], xlim = c(0,limit), xlab = xx_lab,
					horiz = TRUE, las = 1, cex.names = size_lab)
					arrows(y0 = ima, x0 = mu_A_f[length(mu_A_f):1] + eb,
					x1 = mu_A_f[length(mu_A_f):1] - eb, angle = 90, code = 3,
					length = l_edges)
					}
				else{
					ima <- barplot(mu_A_f[length(mu_A_f):1], xlim = c(0,limit), xlab = xx_lab,
					horiz = TRUE, las = 1, cex.names = size_lab, names.arg = c(length(mu_A_f):1))
					arrows(y0 = ima, x0 = mu_A_f[length(mu_A_f):1] + eb,
					x1 = mu_A_f[length(mu_A_f):1] - eb, angle = 90, code = 3,
					length = l_edges)
					}
				}
				##
				dev.off()
				}
			else{
				##
				## produce a pdf file in the working directory
				if(save_file == "pdf"){
					file_name2 <- paste(fname, "_barplot_sa_strength.", save_file, sep = "")
					##
					pdf(file = file_name2)
					##
					{
					if(names_lab == "yes"){
						ima <- barplot(mu_A_f[length(mu_A_f):1], xlim = c(0,limit), xlab = xx_lab,
						horiz = TRUE, las = 1, cex.names = size_lab)
						arrows(y0 = ima, x0 = mu_A_f[length(mu_A_f):1] + eb,
						x1 = mu_A_f[length(mu_A_f):1] - eb, angle = 90, code = 3,
						length = l_edges)
						}
					else{
						ima <- barplot(mu_A_f[length(mu_A_f):1], xlim = c(0,limit), xlab = xx_lab,
						horiz = TRUE, las = 1, cex.names = size_lab, names.arg = c(length(mu_A_f):1))
						arrows(y0 = ima, x0 = mu_A_f[length(mu_A_f):1] + eb,
						x1 = mu_A_f[length(mu_A_f):1] - eb, angle = 90, code = 3,
						length = l_edges)
						}
					}
					##
					dev.off()
					}
				}
			}
			##
			{
			if(names_lab == "yes"){
				ima <- barplot(mu_A_f[length(mu_A_f):1], xlim = c(0,limit), xlab = xx_lab,
				horiz = TRUE, las = 1, cex.names = size_lab)
				arrows(y0 = ima, x0 = mu_A_f[length(mu_A_f):1] + eb,
				x1 = mu_A_f[length(mu_A_f):1] - eb, angle = 90, code = 3,
				length = l_edges)
				}
			else{
				ima <- barplot(mu_A_f[length(mu_A_f):1], xlim = c(0,limit), xlab = xx_lab,
				horiz = TRUE, las = 1, cex.names = size_lab, names.arg = c(length(mu_A_f):1))
				arrows(y0 = ima, x0 = mu_A_f[length(mu_A_f):1] + eb,
				x1 = mu_A_f[length(mu_A_f):1] - eb, angle = 90, code = 3,
				length = l_edges)
				if(V_spa == 1)cat("correspondence between numbers and links visualized in the barplot:\n\n")
				else cat("\ncorrespondence between numbers and links visualized in the barplot:\n\n")
				correspondence <- data.frame(c(1:length(mu_A_f)),names(mu_A_f))
				colnames(correspondence) <- c("number", "link")
				apply(correspondence, 1, function(x){cat(x, sep = "\t"); cat("\n")})
				invisible(correspondence)
				}
			}
		}
	}
	else{
		cat("\nerror: OUT_SIS must be a list generated by the function \"sa_interaction_strength\"")
		cat("\n\n")
		invisible(NULL)
		}
	}
}
