histogram_tnm <- function(DF_TNM = NA, alternative = "two-sided", conf_level = 0.95, 
dataset_ws = "whole", data_type = "count", save_file = "pdf", fname = "community"){
	##
	## error message if the input is not a list object with the following nine elements:
	## [1] CM = community matrix
	## [2] RGT = random graph type
	## [3] NRG = number of random graphs generated
	## [4] TPE = total number of predictions evaluated
	## [5] TCPRE = total number of correct predictions obtained with the reference model
	## [6] TCPRG = total number of correct predictions obtained with the random graphs
	## [7] SPE = number of predictions evaluated for each scenario
	## [8] SCPRE = number of correct predictions obtained for each scenario with the reference model
	## [9] SCPRG = number of correct predictions obtained for each scenario with the random graphs
	##
	nomes_TNM <- c("CM", "RGT", "NRG", "TPE", "TCPRE", "TCPRG", "SPE", "SCPRE", "SCPRG")
	##
	a_allowed <- c("two-sided", "less", "greater")
	cl_allowed <- c(0.90, 0.95, 0.99)
	ds_allowed <- c("whole", "scenario")
	dt_allowed <- c("count", "density")
	all_ext <- c("pdf","svg")
	##
	V_spa <- 0
	##
	{
	if(length(names(DF_TNM)) == 0) l_ml <- 1
	else l_ml <- length(which(is.na(match(names(DF_TNM),nomes_TNM))==TRUE))
	}
	##
	{
	if(is.list(DF_TNM) == TRUE){
		if(l_ml != 0){
			cat("\nerror: DF_TNM must be a list generated by the function \"test_null_model\"")
			cat("\n\n")
			invisible(NULL)
		}
		else{
		##
		## either global results or scenario-specific outcomes can be visualized
		ds_length <- length(which(is.na(match(dataset_ws, ds_allowed))==FALSE))
		if(ds_length != 1){
			cat("\nwarning: the sample quantiles must be defined for either the \"whole\" results or for each \"scenario\"\n")
			cat("dataset_ws was reset to default option (i.e. \"whole\")\n\n")
			dataset_ws = "whole"
			V_spa <- 1
		}
		##
		## either counts or probability densities can be visualized
		dt_length <- length(which(is.na(match(data_type, dt_allowed))==FALSE))
		if(dt_length != 1){
			if(V_spa == 1)cat("warning: either frequencies (\"count\") or probability densities (\"density\") are plotted\n")
			else cat("\nwarning: either frequencies (\"count\") or probability densities (\"density\") are plotted\n")
			cat("data_type was reset to default option (i.e. \"count\")\n\n")
			data_type = "count"
			V_spa <- 1
		}
		##
		## extension for saving the image
		{
		if(length(save_file) > 1 | is.vector(save_file) == FALSE){
			{
			if(V_spa == 1)cat("warning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
			else cat("\nwarning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
			}
			cat("\n")
			cat("the format was reset to default (i.e. \"pdf\")")
			cat("\n\n")
			save_file <- "pdf"
			V_spa <- 1
			}
		else{
			s_ext <- which(all_ext == save_file)
			if(length(s_ext) != 1){
				{
				if(V_spa == 1)cat("warning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
				else cat("\nwarning: the format of the image file must be one of the following: \"pdf\" or \"svg\"")
				}
				cat("\n")
				cat("the format was reset to default (i.e. \"pdf\")")
				cat("\n\n")
				save_file <- "pdf"
				}
			}
		}
		##
		## filename must be a unique element of type character
		{
		if(is.character(fname) == FALSE){
			if(V_spa == 1)cat("warning: the name of the image file must be of type \"character\"\n")
			else cat("\nwarning: the name of the image file must be of type \"character\"\n")
			cat("the name was reset to default option (i.e. \"community\")\n\n")
			fname <- "community"
			V_spa <- 1
			}
		else if(length(fname) > 1){
			if(V_spa == 1)cat("warning: the name of the image file must be a single element of type \"character\"\n")
			else cat("\nwarning: the name of the image file must be a single element of type \"character\"\n")
			cat("the name was reset to default option (i.e. \"community\")\n\n")
			fname <- "community"
			V_spa <- 1
			}
		}
		##
		##
		{
		if(dataset_ws == "whole"){
			file_name <- paste(fname, "_histogram_tnm.", save_file, sep = "")
			##
			## the histogram can be either with counts or probability densities
			xx_v <- as.numeric(names(DF_TNM$TCPRG))
			{
			if(data_type == "count"){
				yy_c <- DF_TNM$TCPRG
				yy_lab <- "count"
				y_lim <- (trunc(max(yy_c)/5) + 1) * 5
				}
			else if(data_type == "density"){
				yy_c <- DF_TNM$TCPRG/sum(DF_TNM$TCPRG)
				yy_lab <- "density"
				y_lim <- (5 * (max(yy_c)*100)%/%5)/100 + .05
				}
			}
			quant <- sample_quantiles(DF_TNM = DF_TNM, alternative = alternative,
			conf_level = conf_level, dataset_ws = dataset_ws)
			l_quant <- length(quant)
			{
			if(l_quant == 1){
				barplot(yy_c , space = 0, col = "white", las = 1,
				xlab = "correct predictions", ylab = yy_lab, ylim = c(0, y_lim))
				abline(v = DF_TNM$TCPRE, col = "#ff0000", lwd = 2)
				abline(v = quant, col = "#000000", lwd = 2, lty = 2)
				##
				##
				{
				if(save_file == "pdf")pdf(file = file_name)
				else if(save_file == "svg")svg(filename = file_name)
				}
				barplot(yy_c , space = 0, col = "white", las = 1,
				xlab = "correct predictions", ylab = yy_lab, ylim = c(0, y_lim))
				abline(v = DF_TNM$TCPRE, col = "#ff0000", lwd = 2)
				abline(v = quant, col = "#000000", lwd = 2, lty = 2)
				dev.off()
				invisible(NULL)
				}
			else if(l_quant == 2){
				barplot(yy_c , space = 0, col = "white", las = 1,
				xlab = "correct predictions", ylab = yy_lab, ylim = c(0, y_lim))
				abline(v = DF_TNM$TCPRE, col = "#ff0000", lwd = 2)
				abline(v = quant[1], col = "#000000", lwd = 2, lty = 2)
				abline(v = quant[2], col = "#000000", lwd = 2, lty = 2)
				##
				##
				{
				if(save_file == "pdf")pdf(file = file_name)
				else if(save_file == "svg")svg(filename = file_name)
				}
				barplot(yy_c , space = 0, col = "white", las = 1,
				xlab = "correct predictions", ylab = yy_lab, ylim = c(0, y_lim))
				abline(v = DF_TNM$TCPRE, col = "#ff0000", lwd = 2)
				abline(v = quant[1], col = "#000000", lwd = 2, lty = 2)
				abline(v = quant[2], col = "#000000", lwd = 2, lty = 2)
				dev.off()
				invisible(NULL)
				}
			}
		}
		else if(dataset_ws == "scenario"){
			n_sce <- length(DF_TNM$SPE)
			quant <- sample_quantiles(DF_TNM = DF_TNM, alternative = alternative,
			conf_level = conf_level, dataset_ws = dataset_ws)
			for(i in 1:n_sce){
				x11()
				##
				## the histogram can be either with counts or probability densities
				{
				if(data_type == "count"){
					{
					if(n_sce == 1){
						yy_c <- DF_TNM$SCPRG
						quant_s1 <- quant
						vert <- DF_TNM$SCPRE
						xx_v <- as.numeric(names(DF_TNM$SCPRG))
						y_lim <- (trunc(max(yy_c)/5) + 1) * 5
						}
					else{
						yy_c <- DF_TNM$SCPRG[i,]
						quant_s1 <- quant[i,]
						vert <- DF_TNM$SCPRE[i]
						xx_v <- as.numeric(colnames(DF_TNM$SCPRG))
						y_lim <- (trunc(max(yy_c)/5) + 1) * 5
						}
					}
					yy_lab <- "count"
					}
				else if(data_type == "density"){
					{
					if(n_sce == 1){
						yy_c <- DF_TNM$SCPRG/sum(DF_TNM$SCPRG)
						quant_s1 <- quant
						vert <- DF_TNM$SCPRE
						xx_v <- as.numeric(names(DF_TNM$SCPRG))
						y_lim <- (5 * (max(yy_c)*100)%/%5)/100 + .05
						}
					else{
						yy_c <- DF_TNM$SCPRG[i,]/sum(DF_TNM$SCPRG[i,])
						quant_s1 <- quant[i,]
						vert <- DF_TNM$SCPRE[i]
						xx_v <- as.numeric(colnames(DF_TNM$SCPRG))
						y_lim <- (5 * (max(yy_c)*100)%/%5)/100 + .05
						}
					}
					yy_lab <- "density"
					}
				}
				##
				l_quant <- length(quant_s1)
				##
				{
				if(l_quant == 1){
					barplot(yy_c , space = 0, col = "white", las = 1,
					xlab = paste("correct predictions - ", i, sep = ""), ylab = yy_lab,
					ylim = c(0, y_lim))
					abline(v = vert, col = "#ff0000", lwd = 2, ylim = c(0, y_lim))
					abline(v = quant_s1, col = "#000000", lwd = 2, lty = 2)
					##
					##
					{
					if(save_file == "pdf")pdf(file = paste(fname, "_", i,
					"_histogram_tnm.", save_file, sep = ""))
					else if(save_file == "svg")svg(filename = paste(fname, "_", i,
					"_histogram_tnm.", save_file, sep = ""))
					}
					barplot(yy_c , space = 0, col = "white", las = 1,
					xlab = paste("correct predictions - ", i, sep = ""), ylab = yy_lab,
					ylim = c(0, y_lim))
					abline(v = vert, col = "#ff0000", lwd = 2)
					abline(v = quant_s1, col = "#000000", lwd = 2, lty = 2)
					dev.off()
					}
				else if(l_quant == 2){
					barplot(yy_c , space = 0, col = "white", las = 1,
					xlab = paste("correct predictions - ", i, sep = ""), ylab = yy_lab,
					ylim = c(0, y_lim))
					abline(v = vert, col = "#ff0000", lwd = 2)
					abline(v = quant_s1[1], col = "#000000", lwd = 2, lty = 2)
					abline(v = quant_s1[2], col = "#000000", lwd = 2, lty = 2)
					##
					##
					{
					if(save_file == "pdf")pdf(file = paste(fname, "_", i,
					"_histogram_tnm.", save_file, sep = ""))
					else if(save_file == "svg")svg(filename = paste(fname, "_", i,
					"_histogram_tnm.", save_file, sep = ""))
					}
					barplot(yy_c , space = 0, col = "white", las = 1,
					xlab = paste("correct predictions - ", i, sep = ""), ylab = yy_lab,
					ylim = c(0, y_lim))
					abline(v = vert, col = "#ff0000", lwd = 2)
					abline(v = quant_s1[1], col = "#000000", lwd = 2, lty = 2)
					abline(v = quant_s1[2], col = "#000000", lwd = 2, lty = 2)
					dev.off()
					}
				}
			}
			invisible(NULL)
			##
			}
		}
		##
		}
	}
	else{
		cat("\nerror: DF_TNM must be a list generated by the function \"test_null_model\"")
		cat("\n\n")
		return(invisible(NULL))
		}
	}
}