levins_concurrent_ns_alt <- function(OUT_LA, DFF = NA, save_file = "yes"){
	##
	## the input must be a list generated by levins_predictions_alternative
	{
	if(is.list(OUT_LA) == TRUE){
		l_li <- length(OUT_LA)
		nomilista <- c("reference_scenario", paste("scenario_",c(1:(l_li-1)), sep = ""))
		{
		if(length(names(OUT_LA)) == 0) l_ml <- 1
		else l_ml <- length(which(is.na(match(names(OUT_LA),nomilista))==TRUE))
		}
		##
		{
		if(l_ml != 0){
			cat("\nerror: OUT_LA must be a list generated by the function \"levins_predictions_alternative\"")
			cat("\n\n")
			invisible(NULL)
		}
		else{
			##
			##
			V_spa <- 0
			SFn <- c("yes", "no")
			SFn_m <- length(which(is.na(match(save_file, SFn))==FALSE))
			if(SFn_m != 1){
				cat("\nwarning: the user can decide whether to save (\"yes\") or not (\"no\") the predictions of all alternative scenarios\n")
				cat("save_file was reset to default option (i.e. \"yes\")\n\n")
				save_file <- "yes"
				V_spa <- 1
			}
			##
			##
			{
			if(V_spa == 1)cat("(1) reference scenario:\n")
			else cat("\n(1) reference scenario:\n")
			}
			{
			if(save_file == "yes")first_round <- levins_concurrent_ns(OUT_LA[[1]],
			DF = DFF, fname = nomilista[1])
			else first_round <- levins_concurrent_ns(OUT_LA[[1]], DF = DFF)
			}
			{
			if(length(first_round) != 0){
				lista_risultati <- as.list(rep(NA,l_li))
				lista_risultati[[1]] <- first_round
				for(i in 1:l_li){
					if(i == 1){
						new_df1 <- rownames(first_round)[1:(length(rownames(first_round))-2)]
						new_s1 <- unlist(lapply(new_df1,function(x)substr(x,1,1)))
						new_s2 <- unlist(lapply(new_df1,function(x)substr(x,2,nchar(x))))
						new_DFF <- cbind(new_s1, new_s2)
					}
					else{
						cat("\n##\n##\n\n")
						cat("\n(", (i), ") alternative topology - scenario ", (i-1), ":\n", sep = "")
						{
						if(save_file == "yes"){
							lista_risultati[[i]] <-levins_concurrent_ns(OUT_LA[[i]], DF = new_DFF,
							fname = nomilista[i])
							}
						else{
							lista_risultati[[i]] <- levins_concurrent_ns(OUT_LA[[i]], DF = new_DFF)
							}
						}
					}
				}
			names(lista_risultati) <- paste("NS_", nomilista, sep = "")
			invisible(lista_risultati)
			}
			else{
				invisible(NULL)
				}
			}
		}
		##
		}
		##
		}
	else{
		cat("\nerror: OUT_LA must be a list generated by the function \"levins_predictions_alternative\"")
		cat("\n\n")
		invisible(NULL)
		}
	}
}
