model_validation_alt <- function(OUT_LA = NA, DFA_list = NA, MV_target_A = NA, scenario = "all"){
	##
	## the input must be a list generated by levins_predictions_alternative
	{
	if(is.list(OUT_LA) == TRUE){
		l_li <- length(OUT_LA)
		nomilista <- c("reference_scenario", paste("scenario_",c(1:(l_li-1)), sep = ""))
		{
		if(length(names(OUT_LA)) == 0) l_ml <- 1
		else l_ml <- length(which(is.na(match(names(OUT_LA),nomilista))==TRUE))
		}
		##
		{
		if(l_ml != 0){
			cat("\nerror: OUT_LA must be a list generated by the function \"levins_predictions_alternative\"")
			cat("\n\n")
			invisible(NULL)
		}
		else{
			##
			##
			V_spa <- 0
			SFn <- c("yes", "no")
			SFn_m <- length(which(is.na(match(save_file, SFn))==FALSE))
			if(SFn_m != 1){
				cat("\nwarning: the user can decide whether to save (\"yes\") or not (\"no\") the predictions of all alternative scenarios\n")
				cat("save_file was reset to default option (i.e. \"yes\")\n\n")
				save_file <- "yes"
				V_spa <- 1
			}
			##
			##
			SCn <- c("all", "symmetric", "foodweb")
			SCn_m <- length(which(is.na(match(scenario, SCn))==FALSE))
			if(SCn_m != 1){
				if(V_spa == 1)cat("warning: the user can decide whether to validate the alternative models according to the following scenarios:\n")
				else cat("\nwarning: the user can decide whether to validate the alternative models according to the following scenarios:\n")
				cat("- all topologies, also with asymmetric interactions (\"all\")\n")
				cat("- symmetric topologies, irrespective of interaction signs (\"symmetric\")\n")
				cat("- all food web topologies with predator-prey interactions(\"foodweb\")\n")
				cat("scenario was reset to default option (i.e. \"all\")\n\n")
				scenario <- "all"
				V_spa <- 1
			}
			##
			##
			{
			if(V_spa == 1)cat("(1) reference scenario:\n")
			else cat("\n(1) reference scenario:\n")
			}
			##
			##
			first_round <- model_validation(OUT_LP = OUT_LA[[1]], DF_list = DFA_list,
			MV_target = MV_target_A, fname = nomilista[1])
			lfr <- length(first_round)
			{
			if(lfr != 0){
				lista_risultati <- as.list(rep(NA,l_li))
				lista_risultati[[1]] <- first_round
				lfr_df <- (lfr - 2)
				DFA_list_AA <- as.list(rep(NA,lfr_df))
				MV_target_AA <- first_round$target
				for(i in 1:l_li){
					if(i == 1){
						for(j in 1:lfr_df){
							DFA_list_AA[[j]] <- first_round[[j]]
						}
					}
					else{
						cat("\n##\n##\n\n")
						cat("\n(", (i), ") alternative topology - scenario ", (i-1), ":\n", sep = "")
						if(scenario == "all"){
							lista_risultati[[i]] <- model_validation(OUT_LA[[i]], DF = DFA_list_AA,
							MV_target = MV_target_AA, fname = nomilista[i])
							}
						else if(scenario == "symmetric"){
								## all elements set to 1 to check for symmetry
								JS <- OUT_LA[[i]][[4]]
								JS[which(OUT_LA[[i]][[4]] != 0)] <- 1
								{
								if(isSymmetric(JS) == TRUE){
									lista_risultati[[i]] <- model_validation(OUT_LA[[i]],
									DF = DFA_list_AA, MV_target = MV_target_AA,
									fname = nomilista[i])
									}
								else{
									lista_risultati[[i]] <- "non_symmetric"
									cat("\nthe topology of the graph is not symmetric\n\n")
									}
								}
							}
							else if(scenario == "foodweb"){
								## all predator-prey links must display asymmetric relations
								JSND <- OUT_LA[[i]][[4]]
								diag(JSND) <- rep(0, nrow(JSND))
								sum_tJ <- apply((JSND + t(JSND)),2,sum)
								l_sum_tJ <- length(which(sum_tJ!=0))
								{
								if(l_sum_tJ == 0){
									lista_risultati[[i]] <- model_validation(OUT_LA[[i]],
									DF = DFA_list_AA, MV_target = MV_target_AA,
									fname = nomilista[i])
									}
								else{
									lista_risultati[[i]] <- "non_foodweb"
									cat("\nthe topology of the graph does not correspond to a foodweb\n\n")
									}
								}
							}
							##
							}
						}
					## }
				## }
				names(lista_risultati) <- paste("MV_", nomilista, sep = "")
				invisible(lista_risultati)
			}
			else{
				invisible(NULL)
				}
			}
		}
		##
		}
		##
		}
	else{
		cat("\nerror: OUT_LA must be a list generated by the function \"levins_predictions_alternative\"")
		cat("\n\n")
		invisible(NULL)
		}
	}
}
