pseudo_p_values <- function(DF_TNM = NA, alternative = "greater", dataset_ws = "whole"){
	##
	## error message if the input is not a list object with the following nine elements:
	## [1] CM = community matrix
	## [2] RGT = random graph type
	## [3] NRG = number of random graphs generated
	## [4] TPE = total number of predictions evaluated
	## [5] TCPRE = total number of correct predictions obtained with the reference model
	## [6] TCPRG = total number of correct predictions obtained with the random graphs
	## [7] SPE = number of predictions evaluated for each scenario
	## [8] SCPRE = number of correct predictions obtained for each scenario with the reference model
	## [9] SCPRG = number of correct predictions obtained for each scenario with the random graphs
	##
	nomes_TNM <- c("CM", "RGT", "NRG", "TPE", "TCPRE", "TCPRG", "SPE", "SCPRE", "SCPRG")
	##
	a_allowed <- c("greater", "less")
	ds_allowed <- c("whole", "scenarios")
	##
	V_spa <- 0
	##
	{
	if(length(names(DF_TNM)) == 0) l_ml <- 1
	else l_ml <- length(which(is.na(match(names(DF_TNM),nomes_TNM))==TRUE))
	}
	##
	{
	if(l_ml == 0){
		##
		## alternative hypothesis must be either "greater" (default) or "less"
		a_length <- length(which(is.na(match(alternative, a_allowed))==FALSE))
		if(a_length != 1){
			cat("\nwarning: alternative hypothesis must be either \"greater\" (default) or \"less\"\n")
			cat("alternative was reset to default option (i.e. \"greater\")\n\n")
			alternative <- "greater"
			V_spa <- 1
		}
		##
		## pseudo p-values must be computed either for the whole results or for each scenario
		ds_length <- length(which(is.na(match(dataset_ws, ds_allowed))==FALSE))
		if(ds_length != 1){
			if(V_spa == 1)cat("warning: the pseudo p-values must be defined for either the \"whole\" results or for each \"scenario\"\n")
			else cat("\nwarning: the pseudo p-values must be defined for either the \"whole\" results or for each \"scenario\"\n")
			cat("dataset_ws was reset to default option (i.e. \"whole\")\n\n")
			dataset_ws = "whole"
		}
		##
		## pseudo p-values
		tot_simul <- DF_TNM$NRG + 1
		{
		if(dataset_ws == "whole"){
			v_d <- DF_TNM$TCPRG
			v_n <- as.integer(names(v_d))
			ref_correct <- DF_TNM$TCPRE
			{
			if(V_spa == 1){
				cat("pseudo p-value of the whole results (alternative hypothesis: ", alternative, "): ", sep = "")
				}
			else {
				cat("\npseudo p-value of the whole results (alternative hypothesis: ", alternative, "): ", sep = "")
				}
			}
			{
			if(alternative == "greater"){
				num_hi <- sum(v_d[which(v_n >= ref_correct)])
				prob_hi <- num_hi/tot_simul
				cat(prob_hi)
				cat("\n\n")
				return(invisible(prob_hi))
				}
			else{
				num_lo <- sum(v_d[which(v_n <= ref_correct)])
				prob_lo <- num_lo/tot_simul
				cat(prob_lo)
				cat("\n\n")
				return(invisible(prob_hi))
				}
			}
			##
			}
		else{
			lunh <- nrow(DF_TNM$SCPRG)
			colu <- 0
			for(j in 1:lunh){
				row_sel <- DF_TNM$SCPRG[j,]
				v_d <- row_sel
				v_n <- as.integer(names(v_d))
				ref_correct_scen <- DF_TNM$SCPRE[j]
				nam_correct_scen <- colnames(DF_TNM$SCPRE)[j]
				{
				if(V_spa == 1 & j == 1){
					cat("pseudo p-value(s) of the scenario(s) results (alternative hypothesis: ", alternative, "):\n\n", sep = "")
					}
				else if(j == 1){
					cat("\npseudo p-value(s) of the scenario(s) results (alternative hypothesis: ", alternative, "):\n\n", sep = "")
					}
				}
				{
				if(alternative == "greater"){
					num_hi <- sum(v_d[which(v_n >= ref_correct_scen)])
					if(j == 1)prob_hi <- num_hi/tot_simul
					else prob_hi <- c(prob_hi, num_hi/tot_simul)
					cat("#", nam_correct_scen, " = ", num_hi/tot_simul, "\n", sep = "")
					if(j == lunh){
						cat("\n")
						names(prob_hi) <- nam_correct_scen
						return(invisible(prob_hi))
						}
					}
				else{
					num_lo <- sum(v_d[which(v_n <= ref_correct_scen)])
					if(j == 1)prob_lo <- num_lo/tot_simul
					else prob_lo <- c(prob_lo, num_lo/tot_simul)
					cat("#", nam_correct_scen, " = ", num_lo/tot_simul, "\n", sep = "")
					if(j == lunh){
						cat("\n")
						names(prob_lo) <- nam_correct_scen
						return(invisible(prob_lo))
						}
					}
				}
			}
			##
			}
		}	
	}
	else{
		cat("\nerror: DF_TNM must be a list generated by the function \"test_null_model\"")
		cat("\n\n")
		return(invisible(NULL))
		}
	}
}