sa_interaction <- function(OUT_LA = NA, fname = "community"){
	##
	## the input must be a list generated by levins_predictions_alternative
	{
	if(is.list(OUT_LA) == TRUE){
		l_li <- length(OUT_LA)
		l_lla <- (l_li - 1)
		nomilista <- c("reference_scenario", paste("scenario_",c(1:l_lla), sep = ""))
		{
		if(length(names(OUT_LA)) == 0) l_ml <- 1
		else l_ml <- length(which(is.na(match(names(OUT_LA),nomilista))==TRUE))
		}
		##
		{
		if(l_ml != 0){
			cat("\nerror: OUT_LA must be a list generated by the function \"levins_predictions_alternative\"")
			cat("\n\n")
			invisible(NULL)
		}
		else{
			##
			## sensitivity analysis for the different graph topologies
			nomen <- c("total number of matrices generated", "total number of stable matrices",
			"probability distribution", "community matrix", "(%) +", "(%) -", "(%) 0",
			"table of predictions")
			{
			if(length(names(OUT_LA[[1]])) == 0) l_cr <- 1
			else l_cr <- length(which(is.na(match(names(OUT_LA[[1]]),nomen))==TRUE))
			}
			##
			{
			if(l_cr != 0){
				cat("\nerror: the first element of OUT_LA must contain results from levins_predictions\n")
				cat("for the reference model to be compared with alternative topologies\n")
				cat("\n\n")
				invisible(NULL)
				}
			else{
				PRED <- OUT_LA[[1]][[8]]
				names_a <- colnames(PRED)
				nodes_l <- length(names_a)
				nodes_p <- nodes_l^2
				graphs <- paste("sc_", c(1:l_lla), sep = "")
				graphs_l <- length(graphs)
				ref_signs <- c(PRED)
				ref_signs_pnz <- ref_signs_pn <- ref_signs
				diff_m <- c(OUT_LA[[1]][[5]] - OUT_LA[[1]][[6]])
				##
				## match considers three main categories (e.g. "?+" and "+" correspond to "+")
				ref_signs_pnz[which(ref_signs == "?+")] <- "+"
				ref_signs_pnz[which(ref_signs == "?-")] <- "-"
				ref_signs_pnz[which(ref_signs == "0*")] <- "0"
				##
				## match considers two categories (i.e. "+" and "-"; "0" is grouped with "-" and
				## ambiguities of "0*" are assigned to either "+" or "-" using diff_m)
				ref_signs_pn[which(diff_m > 0)] <- "+"
				ref_signs_pn[which(diff_m <= 0)] <- "-"
				##
				matches_V <- rep(0,l_lla)
				matches_pnz_V <- matches_pn_V <- matches_V
				##
				JJ <- OUT_LA[[1]][[4]]
				for(i in 1:l_lla){
					if(i == 1)topalter_M <- OUT_LA[[(i+1)]][[4]] - JJ
					else topalter_M <- topalter_M + (OUT_LA[[(i+1)]][[4]] - JJ)
				}
				l_topalter_M <- length(which(topalter_M != 0))
				V_links_nz <- rep(NA,l_topalter_M)
				conte <- 1
				##
				for(i in 1:nodes_l){
					for(j in 1:nodes_l){
						if(topalter_M[i,j] < 0){
							V_links_nz[conte] <- paste(rownames(topalter_M)[i], "-o",
							colnames(topalter_M)[j], sep = " ")
							conte <- conte + 1
						}
						else if(topalter_M[i,j] > 0){
							V_links_nz[conte] <- paste(rownames(topalter_M)[i], "->",
							colnames(topalter_M)[j], sep = " ")
							conte <- conte + 1
						}
					}
				}
				links_scenarios <- matrix(rep(0,(l_lla * l_topalter_M)), nrow = l_lla)
				diff_zero <- unlist(lapply(OUT_LA,function(x)
				length(which((x[[4]]-JJ)!=0))))[2:l_li]
				##
				diff_MATR <- lapply(OUT_LA,function(x)x[[4]]-JJ)
				##
				colnames(links_scenarios) <- V_links_nz
				rownames(links_scenarios) <- graphs
				##
				fr_V <- unlist(lapply(V_links_nz,function(x)strsplit(x, " ")[[1]][1]))
				to_V <- unlist(lapply(V_links_nz,function(x)strsplit(x, " ")[[1]][3]))
				ed_V <- cbind(fr_V,to_V)
				##
				for(i in 1:l_lla){
					simul <- OUT_LA[[(i+1)]]
					##
					simul_signs <- c(simul[[8]])
					##
					simul_signs_pnz <- simul_signs_pn <- simul_signs
					simul_diff_m <- c(simul[[5]] - simul[[6]])
					##
					simul_signs_pnz[which(simul_signs == "?+")] <- "+"
					simul_signs_pnz[which(simul_signs == "?-")] <- "-"
					simul_signs_pnz[which(simul_signs == "0*")] <- "0"
					##
					simul_signs_pn[which(simul_diff_m > 0)] <- "+"
					simul_signs_pn[which(simul_diff_m <= 0)] <- "-"
					##
					comp_1 <- cbind(ref_signs,simul_signs)
					comp_2 <- cbind(ref_signs_pnz,simul_signs_pnz)
					comp_3 <- cbind(ref_signs_pn,simul_signs_pn)
					##
					if(length(unlist(apply(comp_1,1,function(x)which(x[1]!=x[2]))))!=0){
						matches_V[i] <- sum(unlist(apply(comp_1,1,function(x)which(x[1]!=x[2]))))
					}
					if(length(unlist(apply(comp_2,1,function(x)which(x[1]!=x[2]))))!=0){
						matches_pnz_V[i] <- sum(unlist(apply(comp_2,1,function(x)which(x[1]!=x[2]))))
					}
					if(length(unlist(apply(comp_3,1,function(x)which(x[1]!=x[2]))))!=0){
						matches_pn_V[i] <- sum(unlist(apply(comp_3,1,function(x)which(x[1]!=x[2]))))
					}
					##
					for(j in 1:l_topalter_M){
						if(diff_MATR[[(i+1)]][ed_V[j,1],ed_V[j,2]] != 0)links_scenarios[i,j] <- 1
					}
				}
				##
				names(matches_pnz_V) <- names(matches_pn_V) <- names(matches_V) <- graphs
				##
				sa_interactions <- as.list(rep(NA,5))
				sa_interactions[[1]] <- matches_V
				sa_interactions[[2]] <- matches_pnz_V
				sa_interactions[[3]] <- matches_pn_V
				sa_interactions[[4]] <- links_scenarios
				sa_interactions[[5]] <- nodes_l
				names(sa_interactions) <- c("matches_V", "matches_pnz_V",
				"matches_pn_V", "link_scenarios", "tot_nodes")
				##
				cat("\ntotal number of mismatches (all signs preserved) - vector")
				cat("\n\n")
				print(sa_interactions[[1]])
				cat("\n\n")
				cat("total number of mismatches (signs preserved: \"+\", \"-\" and \"0\") - vector")
				cat("\n\n")
				print(sa_interactions[[2]])
				cat("\n\n")
				cat("total number of mismatches (signs preserved: \"+\" and \"-\") - vector")
				cat("\n\n")
				print(sa_interactions[[3]])
				cat("\n\n")
				cat("links considered for each scenario")
				cat("\n\n")
				print(sa_interactions[[4]])
				cat("\n")
				##
				## the list of results is saved in a text file
				{
				if(length(fname) == 1){
					if(is.character(fname) == TRUE){
						file_name_txt <- paste(fname, "_sa_interaction.txt", sep = "")
							}
					else{
						fname <- "community"
						file_name_txt <- paste(fname, "_sa_interaction.txt", sep = "")
						cat("warning: fname must be a single element of type \"character\"\n")
						cat("fname was reset to default (i.e. \"community\")", sep = "")
						cat("\n\n")
						}
				}
				else{
					fname <- "community"
					file_name_txt <- paste(fname, "_sa_interaction.txt", sep = "")
					cat("warning: fname must be a single element of type \"character\"\n")
					cat("fname was reset to default (i.e. \"community\")", sep = "")
					cat("\n\n")
					}
				}
				##
				sink(file_name_txt)
				cat("total number of mismatches (all signs preserved) - vector")
				cat("\n\n")
				print(sa_interactions[[1]])
				cat("\n\n")
				cat("total number of mismatches (signs preserved: \"+\", \"-\" and \"0\") - vector")
				cat("\n\n")
				print(sa_interactions[[2]])
				cat("\n\n")
				cat("total number of mismatches (signs preserved: \"+\" and \"-\") - vector")
				cat("\n\n")
				print(sa_interactions[[3]])
				cat("\n\n")
				cat("links considered for each scenario")
				cat("\n\n")
				print(sa_interactions[[4]])
				sink()
				##
				cat(paste("results are in the file \"", file_name_txt, "\"", sep = ""))
				cat("\n\n")
				##
				invisible(sa_interactions)
				}
			}
		}
		##
		}
		##
		}
	else{
		cat("\nerror: OUT_LA must be a list generated by the function \"levins_predictions_alternative\"")
		cat("\n\n")
		invisible(NULL)
		}
	}
}