sa_interaction_strength <- function(OUT_LP = NA, self_loop = "no",
NTS = 1000, fname = "community"){
	##
	## error message if the input is not a list object with the following eight elements:
	## [1] total number of matrices generated
	## [2] total number of stable matrices
	## [3] probability distribution
	## [4] community matrix
	## [5] (%) +
	## [6] (%) -
	## [7] (%) 0
	## [8] table of predictions
	##
	nomilista <- c("total number of matrices generated", "total number of stable matrices",
	"probability distribution", "community matrix", "(%) +", "(%) -", "(%) 0", "table of predictions")
	{
	if(length(names(OUT_LP)) == 0) l_ml <- 1
	else l_ml <- length(which(is.na(match(names(OUT_LP),nomilista))==TRUE))
	}
	##
	{
	if(is.list(OUT_LP) == TRUE){
		if(l_ml != 0){
			cat("\nerror: OUT_LP must be a list generated by the function \"levins_predictions\"")
			cat("\n\n")
			invisible(NULL)
		}
		##
		## sensitivity analysis for the interaction strength
		else{
			JJ <- OUT_LP[[4]]
			names_a <- colnames(JJ)
			nodes_l <- length(names_a)
			nodes_p <- nodes_l^2
			values <- c(1e-6, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1)
			values_l <- length(values)
			ref_signs <- c(OUT_LP[[8]])
			ref_signs_pnz <- ref_signs_pn <- ref_signs
			diff_m <- c(OUT_LP[[5]] - OUT_LP[[6]])
			##
			## match considers three main categories (e.g. "?+" and "+" correspond to "+")
			ref_signs_pnz[which(ref_signs == "?+")] <- "+"
			ref_signs_pnz[which(ref_signs == "?-")] <- "-"
			ref_signs_pnz[which(ref_signs == "0*")] <- "0"
			##
			## match considers two categories (i.e. "+" and "-"; "0" is grouped with "-" and
			## ambiguities of "0*" are assigned to either "+" or "-" using diff_m)
			ref_signs_pn[which(diff_m > 0)] <- "+"
			ref_signs_pn[which(diff_m <= 0)] <- "-"
			##
			V_spa <- 0
			##
			selfloopn <- c("yes", "no")
			selfloopn_m <- length(which(is.na(match(self_loop, selfloopn))==FALSE))
			if(selfloopn_m != 1){
				cat("\nwarning: the user can decide whether to perform (\"yes\") or not (\"no\") sensitivity analysis for the self-loops:\n")
				cat("self_loop was reset to default option (i.e. \"no\")\n\n")
				self_loop <- "no"
				V_spa <- 1
			}
			##
			NTNn <- c(10, 100, 1000)
			NTNn_m <- length(which(is.na(match(NTS, NTNn))==FALSE))
			if(NTNn_m != 1){
				if(V_spa == 1)cat("warning: the number of runs for levins_predictions must be one of the following: 10, 100 or 1000\n")
				else cat("\nwarning: the number of runs for levins_predictions must be one of the following: 10, 100 or 1000\n")
				cat("NTS was reset to default option (i.e. 1000)\n\n")
				NTS <- 1000
				V_spa <- 1
			}
			##
			JJ_diag <- JJ
			if(self_loop == "no")diag(JJ_diag) <- rep(0,nodes_l)
			tot_links <- length(which(JJ_diag != 0))
			##
			matches_M <- matrix(rep(0,(values_l * tot_links)), nrow = tot_links)
			matches_pnz_M <- matches_pn_M <- matches_M
			names_links <- rep(NA,tot_links)
			coord_links <- matrix(rep(0,tot_links*3), nrow = tot_links)
			##
			cont <- 1
			for(i in 1:nodes_l){
				for(j in 1:nodes_l){
					if(JJ_diag[i,j] != 0){
						{
						if(JJ_diag[i,j] > 0)names_links[cont] <- paste(names_a[i],"->",names_a[j], sep = " ")
						else names_links[cont] <- paste(names_a[i],"-o",names_a[j], sep = " ")
						}
						coord_links[cont,1] <- i
						coord_links[cont,2] <- j
						coord_links[cont,3] <- JJ_diag[i,j]
						M_limits <- matrix(rep(0,nodes_p), nrow = nodes_l)
						for(k in 1:values_l){
							M_limits[coord_links[cont,1],coord_links[cont,2]] <- values[k]
							simul <- levins_predictions_notext(J = JJ,
							INT_MIN = M_limits, INT_MAX = M_limits, NT = NTS)
							##
							simul_signs <- c(simul[[8]])
							##
							simul_signs_pnz <- simul_signs_pn <- simul_signs
							simul_diff_m <- c(simul[[5]] - simul[[6]])
							##	
							simul_signs_pnz[which(simul_signs == "?+")] <- "+"
							simul_signs_pnz[which(simul_signs == "?-")] <- "-"
							simul_signs_pnz[which(simul_signs == "0*")] <- "0"
							##
							simul_signs_pn[which(simul_diff_m > 0)] <- "+"
							simul_signs_pn[which(simul_diff_m <= 0)] <- "-"
							##
							comp_1 <- cbind(ref_signs,simul_signs)
							comp_2 <- cbind(ref_signs_pnz,simul_signs_pnz)
							comp_3 <- cbind(ref_signs_pn,simul_signs_pn)
							##
							if(length(unlist(apply(comp_1,1,function(x)which(x[1]!=x[2]))))!=0){
								matches_M[cont,k] <- sum(unlist(apply(comp_1,1,function(x)which(x[1]!=x[2]))))
							}
							if(length(unlist(apply(comp_2,1,function(x)which(x[1]!=x[2]))))!=0){
								matches_pnz_M[cont,k] <- sum(unlist(apply(comp_2,1,function(x)which(x[1]!=x[2]))))
							}
							if(length(unlist(apply(comp_3,1,function(x)which(x[1]!=x[2]))))!=0){
								matches_pn_M[cont,k] <- sum(unlist(apply(comp_3,1,function(x)which(x[1]!=x[2]))))
							}
						}
						cont <- cont + 1
					}
				}
			}
		colnames(matches_pnz_M) <- colnames(matches_pn_M) <- colnames(matches_M) <- values
		rownames(matches_pnz_M) <- rownames(matches_pn_M) <- rownames(matches_M) <- names_links
		tot_matches_M <- apply(matches_M,1,sum)
		tot_matches_M_pnz <- apply(matches_pnz_M,1,sum)
		tot_matches_M_pn <- apply(matches_pn_M,1,sum)
		##
		colnames(coord_links) <- c("from", "to", "link")
		rownames(coord_links) <- names_links
		##
		sa_interactions <- as.list(rep(NA,7))
		sa_interactions[[1]] <- matches_M
		sa_interactions[[2]] <- tot_matches_M
		sa_interactions[[3]] <- matches_pnz_M
		sa_interactions[[4]] <- tot_matches_M_pnz
		sa_interactions[[5]] <- matches_pn_M
		sa_interactions[[6]] <- tot_matches_M_pn
		sa_interactions[[7]] <- coord_links
		names(sa_interactions) <- c("matches_M", "tot_matches_M", "matches_pnz_M",
		"tot_matches_pnz_M", "matches_pn_M", "tot_matches_pn_M", "edgelist_w")
		##
		{
		if(V_spa == 1)cat("total number of mismatches (all signs preserved) - matrix")
		else cat("\ntotal number of mismatches (all signs preserved) - matrix")
		}
		cat("\n\n")
		print(sa_interactions[[1]])
		cat("\n\n")
		cat("total number of mismatches (all signs preserved) - vector")
		cat("\n\n")
		print(sa_interactions[[2]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\", \"-\" and \"0\") - matrix")
		cat("\n\n")
		print(sa_interactions[[3]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\", \"-\" and \"0\") - vector")
		cat("\n\n")
		print(sa_interactions[[4]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\" and \"-\") - matrix")
		cat("\n\n")
		print(sa_interactions[[5]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\" and \"-\") - vector")
		cat("\n\n")
		print(sa_interactions[[6]])
		cat("\n\n")
		cat("edgelist")
		cat("\n\n")
		print(sa_interactions[[7]])
		cat("\n")
		##
		## the list of results is saved in a text file
		{
		if(length(fname) == 1){
			if(is.character(fname) == TRUE){
				file_name_txt <- paste(fname, "_sa_interaction_strength.txt", sep = "")
					}
			else{
				fname <- "community"
				file_name_txt <- paste(fname, "_sa_interaction_strength.txt", sep = "")
				cat("warning: fname must be a single element of type \"character\"\n")
				cat("fname was reset to default (i.e. \"community\")", sep = "")
				cat("\n\n")
				}
		}
		else{
			fname <- "community"
			file_name_txt <- paste(fname, "_sa_interaction_strength.txt", sep = "")
			cat("warning: fname must be a single element of type \"character\"\n")
			cat("fname was reset to default (i.e. \"community\")", sep = "")
			cat("\n\n")
			}
		}
		##
		sink(file_name_txt)
		cat("total number of mismatches (all signs preserved) - matrix")
		cat("\n\n")
		print(sa_interactions[[1]])
		cat("\n\n")
		cat("total number of mismatches (all signs preserved) - vector")
		cat("\n\n")
		print(sa_interactions[[2]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\", \"-\" and \"0\") - matrix")
		cat("\n\n")
		print(sa_interactions[[3]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\", \"-\" and \"0\") - vector")
		cat("\n\n")
		print(sa_interactions[[4]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\" and \"-\") - matrix")
		cat("\n\n")
		print(sa_interactions[[5]])
		cat("\n\n")
		cat("total number of mismatches (signs preserved: \"+\" and \"-\") - vector")
		cat("\n\n")
		print(sa_interactions[[6]])
		cat("\n\n")
		cat("edgelist")
		cat("\n\n")
		print(sa_interactions[[7]])
		sink()
		##
		cat(paste("results are in the file \"", file_name_txt, "\"", sep = ""))
		cat("\n\n")
		##
		invisible(sa_interactions)
		}
	}
	else{
		cat("\nerror: OUT_LP must be a list generated by the function \"levins_predictions\"")
		cat("\n\n")
		invisible(NULL)
		}
	}
}